environment:
  matrix:
    - GENERATOR_NAME: "Visual Studio 14 2015"
    - GENERATOR_NAME: "Visual Studio 14 2015 Win64"
    - GENERATOR_NAME: "Visual Studio 14 2015 ARM"
    - GENERATOR_NAME: "MinGW Makefiles"

platform: x64
configuration: Release

install:
  - git submodule update --init --recursive

build_script:
  - C:\projects\pksav\testing\appveyor-scripts\build-test.bat
