environment:
  matrix:
    - CMAKE_DASH_G: "Visual Studio 14 2015"
    - CMAKE_DASH_G: "Visual Studio 14 2015 Win64"
    - CMAKE_DASH_G: "Visual Studio 14 2015 ARM"

platform: x64
configuration: Release

install:
  - git submodule update --init --recursive

build_script:
  - C:\projects\pksav\testing\appveyor-scripts\build-test.bat
