os: Visual Studio 2015

install:
  - git submodule update --init --recursive

platform: x64
configuration: Release

build:
  project: ALL_BUILD.vcxproj

before_build:
  - mkdir c:\projects\pksav\build
  - cd c:\projects\pksav\build
  - cmake -G "Visual Studio 14 2015 Win64" ..

after_build:
  - ctest --output-on-failure
